build: false

     
branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt
  - flake8
  - isort --check-only --recursive .

install:
  - python setup.py -q develop

before_script:
  - mkdir docs/source/_static
  - sphinx-build -W -b html docs/source docs/_build

  
test_script:
   - nosetests --with-coverage --cover-package=netjsonconfig
