build: false

environment:
  matrix:
      - PYTHON_VERSION: 2.7
      - PYTHON_VERSION: 3.4
      
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt
  - flake8
  - isort --check-only --recursive .

  - python setup.py -q develop

  - mkdir docs/source/_static
  - sphinx-build -W -b html docs/source docs/_build
  
test_script:
   - nosetests --with-coverage --cover-package=netjsonconfig
