build: false

environment:
  matrix:
      - PYTHON_VERSION: 2.7
        MINICONDA: C:\Miniconda

      
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pip setuptools wheel nose"
  - activate test-environment
  - pip install -r requirements-test.txt

  - python setup.py -q develop

  
test_script:
   - nosetests --with-coverage --cover-package=netjsonconfig
